config/routes.rb
SpendALot::Application.routes.draw do

  resources :trends do
    collection do
      match ':slug' => 'trends#category', :as => :category, via: [:get]
      match 'trends/:slug/:year/:month' => 'trends#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :category_monthly, via: [:get]
    end
  end

  resources :categories do
    collection do
      post 'assign'
      match 'ajax-by-keyword' => 'categories#ajax_by_keyword', via: [:get]
    end
  end

  resources :expenses do
    collection do
      get 'descriptions'
      get 'download'
      match ':year/:month' => 'expenses#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :monthly, via: [:get]
    end
  end

  resources :keywords

  resources :statements do
    collection do
      get 'delete'
      post 'csv'
      post 'load'
      post 'upload'
      post 'wesabe'
    end
  end

  root :to => 'home#index', :as => :home

end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  before_filter :set_categories

  def index
    expenses = Expense.order('date DESC')
    @expenses_months = expenses.group_by { |e| e.date.beginning_of_month }
  end

  def category
    @category = Category.where(:slug => params[:slug]).first
    if @category.nil?
      redirect_to :status => 404
    end
    
    @monthly_data = @category.monthly_data
    @yearly_data = @category.yearly_data
    @months = @monthly_data.keys
    @average = @category.average(@monthly_data)
    current_month = Date.today.strftime('%b %Y')
    if @monthly_data.has_key?(current_month)
      @current_expense = @monthly_data[current_month][:sum]
    else
      @current_expense = 0
    end
    @difference = @current_expense - @average

    respond_to do |format|
      format.html
      format.json { render :json => @monthly_data }
    end
  end

  def monthly
    @category = Category.where(:slug => params[:slug]).first
    if @category.nil?
      redirect_to :status => 404
    end
   
    @month = Date.new(params[:year].to_i, params[:month].to_i)
    @expenses = @category.expenses.where(:date => @month..@month.end_of_month).order(:date)

    @monthly_data = @category.monthly_data
    @average = @category.average(@monthly_data)

    @current_expense = @expenses.sum(:amount)
    @difference = @current_expense - @average

    render :action => 'monthly'
  end

  private
    def set_categories
      @categories = Rails.cache.read('categories')
      if @categories.nil?
        @categories = Category.all
        Rails.cache.write('categories', @categories)
      end
    end
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/trends/category.html.erb
<h3><%= @category.name %></h3>
<div id="category"></div>

<div>
  Monthly average: <%= number_with_precision(@average, :precision => 2)  %>
</div>
<div>
  Current expense: <%= number_with_precision(@current_expense, :precision => 2) %>
</div>
<div>
  You are
  <% if @difference >= 0 %>
    above
  <% else %>
    below
  <% end %>
  the monthly average by <%= number_with_precision(@difference, :precision => 2) %>
</div>

<h3>Year</h3>
<table class="expense">
<% @yearly_data.reverse_each do |month, dict| %>
  <tr>
    <td><%= dict[:date].year %></td>
    <td class="amount"><%= number_with_precision(dict[:sum], :precision => 2) %></td>
  </tr>
<% end %>
</table>

<h3>Month</h3>
<table class="expense">
<% @monthly_data.reverse_each do |month, dict| %>
  <tr>
    <td><%= link_to month, category_monthly_trends_path(@category.slug, dict[:date].year, dict[:date].month) %></td>
    <td class="amount"><%= number_with_precision(dict[:sum], :precision => 2) %></td>
  </tr>
<% end %>
</table>

<input type="hidden" id="category-id" value="<%= @category.id %>" />
<input type="hidden" id="category-name" value="<%= @category.name %>" />
<input type="hidden" id="category-slug" value="<%= @category.slug %>" />

app/views/trends/index.html.erb
<h2>Trends</h2>

<table id="monthly-expenses">
  <tr>
    <th>Month</th>
    <th>Amount</th>
  </tr>
<% @expenses_months.each do |month, expenses| %>
  <tr>
    <td><%= month.strftime("%B %Y") %></td>
    <td class="amount"><%= number_with_precision(expenses.sum(&:amount), :precision => 2) %></td>
  </tr>
<% end %>
</table>

<% @expenses_months.each do |month, expenses| %>
  <h2><%= month.strftime("%B %Y") %></h2>
  <% for expense in expenses %>
    <div class="expense">
      <%= expense.date.to_date.to_s(:long) %> -
      <strong><%= expense.description %></strong> -
      <%= expense.amount_display %>
    </div>
  <% end %>
<% end %>

app/views/trends/monthly.html.erb
<h4><%= link_to @category.name, category_trends_path(@category.slug) %> - <%= @month.strftime('%B %Y') %></h4>

<div>
  Monthly average: <%= number_with_precision(@average, :precision => 2)  %>
</div>
<div>
  Monthly total: <%= number_with_precision(@current_expense, :precision => 2) %>
</div>
<div>
  You are
  <% if @difference >= 0 %>
    above
  <% else %>
    below
  <% end %>
  the monthly average by <%= number_with_precision(@difference, :precision => 2) %>
</div>
<br />

<table class="expense">
<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.date.strftime('%b %d') %></td>
    <td><%= expense.description %></td>
    <td class="amount"><%= number_with_precision(expense.amount, :precision => 2) %></td>
  </tr>
<% end %>
</table>