config/routes.rb
SpendALot::Application.routes.draw do

  resources :trends do
    collection do
      match ':slug' => 'trends#category', :as => :category, via: [:get]
      match 'trends/:slug/:year/:month' => 'trends#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :category_monthly, via: [:get]
    end
  end

  resources :categories do
    collection do
      post 'assign'
      match 'ajax-by-keyword' => 'categories#ajax_by_keyword', via: [:get]
    end
  end

  resources :expenses do
    collection do
      get 'descriptions'
      get 'download'
      match ':year/:month' => 'expenses#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :monthly, via: [:get]
    end
  end

  resources :keywords

  resources :statements do
    collection do
      get 'delete'
      post 'csv'
      post 'load'
      post 'upload'
      post 'wesabe'
    end
  end

  root :to => 'home#index', :as => :home

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :words
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords
  # GET /keywords.xml
  def index
    @keywords = Keyword.joins(:category).order('name', 'words')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @keywords }
    end
  end

  # GET /keywords/1
  # GET /keywords/1.xml
  def show
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @keyword }
    end
  end

  # GET /keywords/new
  # GET /keywords/new.xml
  def new
    @keyword = Keyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @keyword }
    end
  end

  # GET /keywords/1/edit
  def edit
    @keyword = Keyword.find(params[:id])
  end

  # POST /keywords
  # POST /keywords.xml
  def create
    @keyword = Keyword.new(params[:keyword])


    respond_to do |format|
      if @keyword.save
        if params['add-another']
          flash[:notice] = 'Keyword created'
          return redirect_to :action => 'new'
        end
        format.html { redirect_to(@keyword, :notice => 'Keyword was successfully created.') }
        format.xml  { render :xml => @keyword, :status => :created, :location => @keyword }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @keyword.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /keywords/1
  # PUT /keywords/1.xml
  def update
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      if @keyword.update_attributes(params[:keyword].permit(:category_id, :words))
        format.html { redirect_to(@keyword, :notice => 'Keyword was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @keyword.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.xml
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to(keywords_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :words %><br />
    <%= f.text_field :words %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= select("keyword", "category_id", Category.all.collect {|c| [c.name, c.id]}, {:include_blank => '---'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= submit_tag "Create and Add another", :name => "add-another" %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<p>
<%= link_to 'New Keyword', new_keyword_path %>
</p>

<table>
  <tr>
    <th>Words</th>
    <th>Category</th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.each do |keyword| %>
  <tr>
    <td><%= link_to keyword.words, edit_keyword_path(keyword) %></td>
    <td><%= keyword.category.name if keyword.category %></td>
    <td><%= link_to 'Destroy', keyword, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Words:</b>
  <%= @keyword.words %>
</p>


<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>