config/routes.rb
SpendALot::Application.routes.draw do

  resources :trends do
    collection do
      match ':slug' => 'trends#category', :as => :category, via: [:get]
      match 'trends/:slug/:year/:month' => 'trends#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :category_monthly, via: [:get]
    end
  end

  resources :categories do
    collection do
      post 'assign'
      match 'ajax-by-keyword' => 'categories#ajax_by_keyword', via: [:get]
    end
  end

  resources :expenses do
    collection do
      get 'descriptions'
      get 'download'
      match ':year/:month' => 'expenses#monthly', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :as => :monthly, via: [:get]
    end
  end

  resources :keywords

  resources :statements do
    collection do
      get 'delete'
      post 'csv'
      post 'load'
      post 'upload'
      post 'wesabe'
    end
  end

  root :to => 'home#index', :as => :home

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpendALot</title>
  <%= stylesheet_link_tag "base", media: "all" %>
  <%= stylesheet_link_tag "expenses", media: "all" %>
  <%= stylesheet_link_tag "scaffold", media: "all" %>
  <%= stylesheet_link_tag "trends", media: "all" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" %>
  <%= javascript_include_tag "jquery.min" %>
  <%= javascript_include_tag "jquery-ui.min" %>
  <%= javascript_include_tag "rails" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://www.google.com/jsapi" %>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['corechart']});
  </script>
  <%= javascript_include_tag "gcolumn_chart" %>
  <%= javascript_include_tag "pie_chart" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <h1><%= link_to "Spend a Lot", home_path %></h1>
    <div id="top-navigation">
      <div>
      <% if request.fullpath == '/' %>
         Overview
      <% else %>
        <%= link_to "Overview", home_path %>
      <% end %>
      </div>
      <div>
      <% if request.fullpath.include? 'expenses' %>
        Expenses
      <% else %>
        <%= link_to "Expenses", expenses_path %>
      <% end %>
      </div>
      <div>
      <% if request.fullpath.include? 'trends' %>
        Trends
      <% else %>
        <%= link_to "Trends", trends_path %>
      <% end %>
      </div>
    </div>
  </div>
  <div id="content">
    <% if flash.notice %>
    <div id="flash-messages">
      <%= flash.notice %>
    </div>
    <% end %>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </div>
</body>
</html>

app/views/layouts/trends.html.erb
<% content_for :content do %>
  <b>Trending:</b>
  <% @categories.each do |category| %>
    <% if @category and @category.name == category.name %>
      <b><%= category.name %></b> |
    <% else %>
      <%= link_to category.name, category_trends_path(category.slug) %> |
    <% end %>
  <% end %>
  <%= yield %>
<% end %>

<%= render :file => "layouts/application" %>